<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My awesome page</title>
</head>
 <body>
      <h1>Контрольна робота</h1>
      <h2>Сухолитка Каріна Миколаївна</h2>
      <h3>Варіант 2</h3>
 
      <h5>Текст</h5>
      
      <h4>Список продуктів:</h4>
      <ul>
        <li>Чай</li>
        <li>Овочі:</li>
        <li>1. Капуста</li>
        <li>2. Морква</li>
        <li>3. Буряк</li>
        <li>Сир</li>
        <li>Сметана</li>
        <li>Кетчуп</li>
      </ul>
      <title>https://place-hold.it/</title>
      <table border="1">
        <tr>
          <th>Місто</th>
          <th>Населення</th>
        </tr>
        <tr>
          <td>Дублін</td>
          <td>1,1 млн. ос.</td>
        </tr>
        <tr>
          <td>Ер-Ріяд</td>
          <td>7,6 млн. ос.</td>
        </tr>
        <tr>
          <td>Мюнхен</td>
          <td>1,4 млн. ос.</td>
        </tr>
        <tr>
          <td>Детройт</td>
          <td>0,6 млн. ос.</td>
        </tr>
      </table>
      <img src="red.gif" alt="red">
 </body>
</html>
